export interface TestDefinition {
  name: string
  url?: string
  baitClass?: string
  baitId?: string
}

export interface TestCategory {
  id: string
  name: string
  tests: TestDefinition[]
}

export const TEST_CATEGORIES: TestCategory[] = [
  {
    id: 'cosmetic-filters',
    name: 'Filtry kosmetyczne (ukrywanie elementów)',
    tests: [
      { name: 'Klasa .ad', baitClass: 'ad' },
      { name: 'Klasa .ads', baitClass: 'ads' },
      { name: 'Klasa .adsbox', baitClass: 'adsbox' },
      { name: 'Klasa .ad-banner', baitClass: 'ad-banner' },
      { name: 'Klasa .ad-placeholder', baitClass: 'ad-placeholder' },
      { name: 'Klasa .ad-wrapper', baitClass: 'ad-wrapper' },
      { name: 'Klasa .adUnit', baitClass: 'adUnit' },
      { name: 'Klasa .textAd', baitClass: 'textAd' },
      { name: 'Klasa .banner-ad', baitClass: 'banner-ad' },
      { name: 'Klasa .pub_300x250', baitClass: 'pub_300x250' },
      { name: 'Klasa .sponsoredAd', baitClass: 'sponsoredAd' },
      { name: 'Klasa .ad-leaderboard', baitClass: 'ad-leaderboard' },
      { name: 'ID #ad_box', baitId: 'ad_box' },
      { name: 'ID #ads-banner', baitId: 'ads-banner' },
      { name: 'ID #google_ads', baitId: 'google_ads' },
      { name: 'ID #ad-container', baitId: 'ad-container' },
    ],
  },
  {
    id: 'google-ads',
    name: 'Google Ads / AdSense / AdMob',
    tests: [
      { name: 'Google AdSense', url: 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js' },
      { name: 'Google Ads', url: 'https://www.googleadservices.com/pagead/conversion.js' },
      { name: 'DoubleClick GPT', url: 'https://securepubads.g.doubleclick.net/tag/js/gpt.js' },
      { name: 'DoubleClick Ad', url: 'https://ad.doubleclick.net/ddm/activity/' },
      { name: 'Google Funding Choices', url: 'https://fundingchoicesmessages.google.com/i/pub-0000000000000000' },
      { name: 'Google Ad Manager', url: 'https://pubads.g.doubleclick.net/gampad/ads' },
      { name: 'Google IMA SDK', url: 'https://imasdk.googleapis.com/js/sdkloader/ima3.js' },
      { name: 'Google AdMob', url: 'https://admob-sdk.google.com/adunit' },
      { name: 'Google Partner Ads', url: 'https://www.google.com/adsense/search/async-ads.js' },
      { name: 'pagead2.googleadservices.com', url: 'https://pagead2.googleadservices.com/' },
      { name: 'stats.g.doubleclick.net', url: 'https://stats.g.doubleclick.net/' },
      { name: 'static.doubleclick.net', url: 'https://static.doubleclick.net/' },
      { name: 'm.doubleclick.net', url: 'https://m.doubleclick.net/' },
      { name: 'mediavisor.doubleclick.net', url: 'https://mediavisor.doubleclick.net/' },
    ],
  },
  {
    id: 'ad-networks',
    name: 'Sieci reklamowe',
    tests: [
      { name: 'Amazon Ads', url: 'https://z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US' },
      { name: 'Amazon Ads Tag', url: 'https://s.amazon-adsystem.com/iu3?cm3ppClass=jor498' },
      { name: 'Amazon analyticsengine', url: 'https://analyticsengine.s3.amazonaws.com/' },
      { name: 'Amazon analytics S3', url: 'https://analytics.s3.amazonaws.com/' },
      { name: 'Amazon advice-ads', url: 'https://advice-ads.s3.amazonaws.com/' },
      { name: 'Media.net', url: 'https://contextual.media.net/dmedianet.js' },
      { name: 'static.media.net', url: 'https://static.media.net/' },
      { name: 'media.net', url: 'https://media.net/' },
      { name: 'adservetx.media.net', url: 'https://adservetx.media.net/' },
      { name: 'Outbrain', url: 'https://widgets.outbrain.com/outbrain.js' },
      { name: 'Taboola', url: 'https://cdn.taboola.com/libtrc/loader.js' },
      { name: 'Criteo', url: 'https://static.criteo.net/js/ld/publishertag.prebid.js' },
      { name: 'AppNexus', url: 'https://ib.adnxs.com/ut/v3/prebid' },
      { name: 'Rubicon', url: 'https://fastlane.rubiconproject.com/a/api/fastlane.json' },
      { name: 'Index Exchange', url: 'https://htlb.casalemedia.com/headertag' },
      { name: 'ShareThrough', url: 'https://platform-api.sharethrough.com/v2.0/creative/stx-monetize' },
      { name: 'Sovrn', url: 'https://ap.lijit.com/rtb/bid' },
      { name: 'Yahoo Ads', url: 'https://s.yimg.com/rq/darla/4-0-0/html/r-sf.html' },
      { name: 'Ezoic', url: 'https://g.ezoic.net/ezoic/ezoic.js' },
      { name: 'Revcontent', url: 'https://assets.revcontent.com/master/delivery.js' },
      { name: 'MGID', url: 'https://jsc.mgid.com/site.js' },
      { name: 'PropellerAds', url: 'https://go.onclasrv.com/apu.php' },
      { name: 'PopAds', url: 'https://c1.popads.net/pop.js' },
      { name: 'Adsterra', url: 'https://www.profitabledisplaynetwork.com/b4.js' },
      { name: 'Infolinks', url: 'https://resources.infolinks.com/js/infolinks_main.js' },
      { name: 'Vibrant Media', url: 'https://ads.intellitxt.com/intellitxt/front.asp' },
      { name: 'TripleLift', url: 'https://tlx.3lift.com/header/auction' },
      { name: 'AdRoll', url: 'https://s.adroll.com/j/roundtrip.js' },
      { name: 'TradeDesk', url: 'https://js.adsrvr.org/up_loader.1.1.0.js' },
      { name: 'AdColony ads30', url: 'https://ads30.adcolony.com/' },
      { name: 'AdColony adc3-launch', url: 'https://adc3-launch.adcolony.com/' },
      { name: 'AdColony events3alt', url: 'https://events3alt.adcolony.com/' },
    ],
  },
  {
    id: 'polish-ads',
    name: 'Polskie sieci reklamowe',
    tests: [
      { name: 'WP Ads (Wirtualna Polska)', url: 'https://std.wpcdn.pl/wpjslib/wpjslib-inline.js' },
      { name: 'Gemius', url: 'https://gapl.hit.gemius.pl/gplayer.js' },
      { name: 'SALESmanago', url: 'https://app2.salesmanago.pl/static/sm.js' },
      { name: 'Allegro Analytics', url: 'https://analytics.allegro.pl/collector' },
      { name: 'mBank Analytics', url: 'https://ww3.mbank.pl/analytics.js' },
      { name: 'IdeoForce', url: 'https://widget.ideoforce.com/widget.js' },
      { name: 'Adrino', url: 'https://adrino.pl/adx/request' },
      { name: 'adocean', url: 'https://myao.adocean.pl/files/js/ado.js' },
    ],
  },
  {
    id: 'tracking-analytics',
    name: 'Tracking i analityka',
    tests: [
      { name: 'Google Analytics', url: 'https://www.google-analytics.com/analytics.js' },
      { name: 'Google Analytics 4', url: 'https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX' },
      { name: 'analytics.google.com', url: 'https://analytics.google.com/' },
      { name: 'ssl.google-analytics.com', url: 'https://ssl.google-analytics.com/' },
      { name: 'Facebook Pixel', url: 'https://connect.facebook.net/en_US/fbevents.js' },
      { name: 'Hotjar', url: 'https://static.hotjar.com/c/hotjar-0.js' },
      { name: 'Hotjar adm', url: 'https://adm.hotjar.com/' },
      { name: 'Hotjar insights', url: 'https://insights.hotjar.com/' },
      { name: 'Hotjar script', url: 'https://script.hotjar.com/' },
      { name: 'Hotjar surveys', url: 'https://surveys.hotjar.com/' },
      { name: 'Hotjar careers', url: 'https://careers.hotjar.com/' },
      { name: 'Hotjar events', url: 'https://events.hotjar.io/' },
      { name: 'Mixpanel', url: 'https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js' },
      { name: 'Heap Analytics', url: 'https://cdn.heapanalytics.com/js/heap-0.js' },
      { name: 'Amplitude', url: 'https://cdn.amplitude.com/libs/amplitude-8.21.4-min.gz.js' },
      { name: 'FullStory', url: 'https://edge.fullstory.com/s/fs.js' },
      { name: 'Clarity (Microsoft)', url: 'https://www.clarity.ms/tag/XXXXXXXXX' },
      { name: 'Lucky Orange', url: 'https://d10lpsik1i8c69.cloudfront.net/w.js' },
      { name: 'luckyorange.com', url: 'https://luckyorange.com/' },
      { name: 'api.luckyorange.com', url: 'https://api.luckyorange.com/' },
      { name: 'cdn.luckyorange.com', url: 'https://cdn.luckyorange.com/' },
      { name: 'w1.luckyorange.com', url: 'https://w1.luckyorange.com/' },
      { name: 'upload.luckyorange.net', url: 'https://upload.luckyorange.net/' },
      { name: 'cs.luckyorange.net', url: 'https://cs.luckyorange.net/' },
      { name: 'settings.luckyorange.net', url: 'https://settings.luckyorange.net/' },
      { name: 'mouseflow.com', url: 'https://mouseflow.com/' },
      { name: 'o2.mouseflow.com', url: 'https://o2.mouseflow.com/' },
      { name: 'gtm.mouseflow.com', url: 'https://gtm.mouseflow.com/' },
      { name: 'api.mouseflow.com', url: 'https://api.mouseflow.com/' },
      { name: 'tools.mouseflow.com', url: 'https://tools.mouseflow.com/' },
      { name: 'cdn-test.mouseflow.com', url: 'https://cdn-test.mouseflow.com/' },
      { name: 'Crazy Egg', url: 'https://script.crazyegg.com/pages/scripts/0000/0000.js' },
      { name: 'Optimizely', url: 'https://cdn.optimizely.com/js/0.js' },
      { name: 'VWO', url: 'https://dev.visualwebsiteoptimizer.com/lib/0.js' },
      { name: 'Plausible', url: 'https://plausible.io/js/script.js' },
      { name: 'New Relic', url: 'https://js-agent.newrelic.com/nr-spa-1216.min.js' },
      { name: 'Sentry', url: 'https://browser.sentry-cdn.com/7.0.0/bundle.min.js' },
      { name: 'Tealium', url: 'https://tags.tiqcdn.com/utag/main/prod/utag.js' },
      { name: 'Snowplow', url: 'https://d1fc8wv8zag5ca.cloudfront.net/2.18.2/sp.js' },
      { name: 'Chartbeat', url: 'https://static.chartbeat.com/js/chartbeat.js' },
      { name: 'Comscore', url: 'https://sb.scorecardresearch.com/beacon.js' },
      { name: 'Nielsen', url: 'https://cdn-gl.imrworldwide.com/conf/0.js' },
      { name: 'Quantcast', url: 'https://secure.quantserve.com/quant.js' },
      { name: 'Keen.io', url: 'https://d26b395fwzu5fz.cloudfront.net/keen-tracking-1.4.0.min.js' },
      { name: 'Kissmetrics', url: 'https://scripts.kissmetrics.com/0.js' },
      { name: 'Parse.ly', url: 'https://cdn.parsely.com/keys/0/p.js' },
      { name: 'FreshWorks', url: 'https://freshmarketer.com/' },
      { name: 'FreshWorks claritybt', url: 'https://claritybt.freshmarketer.com/' },
      { name: 'stats.wp.com', url: 'https://stats.wp.com/' },
    ],
  },
  {
    id: 'social-trackers',
    name: 'Trackery społecznościowe',
    tests: [
      { name: 'Facebook SDK', url: 'https://connect.facebook.net/en_US/sdk.js' },
      { name: 'Facebook Social Plugin', url: 'https://www.facebook.com/plugins/like.php' },
      { name: 'pixel.facebook.com', url: 'https://pixel.facebook.com/' },
      { name: 'Twitter Widget', url: 'https://platform.twitter.com/widgets.js' },
      { name: 'Twitter Analytics', url: 'https://static.ads-twitter.com/uwt.js' },
      { name: 'LinkedIn Insight', url: 'https://snap.licdn.com/li.lms-analytics/insight.min.js' },
      { name: 'LinkedIn Ads', url: 'https://px.ads.linkedin.com/collect' },
      { name: 'ads.linkedin.com', url: 'https://ads.linkedin.com/' },
      { name: 'analytics.pointdrive.linkedin.com', url: 'https://analytics.pointdrive.linkedin.com/' },
      { name: 'Pinterest Tag', url: 'https://s.pinimg.com/ct/core.js' },
      { name: 'ads.pinterest.com', url: 'https://ads.pinterest.com/' },
      { name: 'log.pinterest.com', url: 'https://log.pinterest.com/' },
      { name: 'TikTok Pixel', url: 'https://analytics.tiktok.com/i18n/pixel/sdk.js' },
      { name: 'ads-sg.tiktok.com', url: 'https://ads-sg.tiktok.com/' },
      { name: 'business-api.tiktok.com', url: 'https://business-api.tiktok.com/' },
      { name: 'ads.tiktok.com', url: 'https://ads.tiktok.com/' },
      { name: 'Snapchat Pixel', url: 'https://sc-static.net/scevent.min.js' },
      { name: 'Reddit Pixel', url: 'https://www.redditstatic.com/ads/pixel.js' },
      { name: 'YouTube Ads', url: 'https://ads.youtube.com/' },
      { name: 'ShareThis', url: 'https://platform-api.sharethis.com/js/sharethis.js' },
      { name: 'AddThis', url: 'https://s7.addthis.com/js/300/addthis_widget.js' },
      { name: 'Disqus', url: 'https://disqus.com/embed/comments/' },
      { name: 'Instagram Embed', url: 'https://www.instagram.com/embed.js' },
      { name: 'Vk Widget', url: 'https://vk.com/js/api/openapi.js' },
    ],
  },
  {
    id: 'error-trackers',
    name: 'Error Trackery',
    tests: [
      { name: 'Bugsnag notify', url: 'https://notify.bugsnag.com/' },
      { name: 'Bugsnag sessions', url: 'https://sessions.bugsnag.com/' },
      { name: 'Bugsnag API', url: 'https://api.bugsnag.com/' },
      { name: 'Bugsnag app', url: 'https://app.bugsnag.com/' },
      { name: 'Sentry app', url: 'https://app.getsentry.com/' },
    ],
  },
  {
    id: 'fingerprinting',
    name: 'Fingerprinting i śledzenie zaawansowane',
    tests: [
      { name: 'FingerprintJS', url: 'https://cdn.jsdelivr.net/npm/@fingerprintjs/fingerprintjs@3/dist/fp.min.js' },
      { name: 'ID5', url: 'https://cdn.id5-sync.com/api/1.0/id5-api.js' },
      { name: 'LiveRamp', url: 'https://launch.ats.rlcdn.com/ats.min.js' },
      { name: 'BlueCava', url: 'https://config.bluecava.com/v8/bc.js' },
      { name: 'Session Replay (LogRocket)', url: 'https://cdn.lr-in-prod.com/LogRocket.min.js' },
      { name: 'Session Replay (Smartlook)', url: 'https://web-sdk.smartlook.com/recorder.js' },
      { name: 'WebTrends', url: 'https://s.webtrends.com/js/webtrends.min.js' },
      { name: 'Bombora', url: 'https://tag.brandcdn.com/autoscript/bomboracom_rxm2psmjr3dw80co/Bombora.js' },
      { name: 'Lotame', url: 'https://tags.crwdcntrl.net/lt/c/0/sync.min.js' },
      { name: 'Oracle BlueKai', url: 'https://tags.bluekai.com/site/0' },
      { name: 'MediaMath', url: 'https://pixel.mathtag.com/event/js' },
      { name: 'Zeotap', url: 'https://content.zeotap.com/sdk/idp.min.js' },
    ],
  },
  {
    id: 'popups-redirects',
    name: 'Popupy, popundery i przekierowania',
    tests: [
      { name: 'PopAds', url: 'https://c1.popads.net/pop.js' },
      { name: 'PopCash', url: 'https://cdn.popcash.net/pop.js' },
      { name: 'PopMyAds', url: 'https://cdn.popmyads.com/pop.js' },
      { name: 'RevenueHits', url: 'https://ads.revenuehits.com/api/serve.js' },
      { name: 'HilltopAds', url: 'https://ssp.hilltopads.com/?type=popup' },
      { name: 'JuicyAds', url: 'https://js.juicyads.com/jads.js' },
      { name: 'TrafficJunky', url: 'https://cdn.trafficjunky.net/ads/js/v2/tj_loader.js' },
      { name: 'AdCash', url: 'https://www.adcash.com/script/java.php' },
      { name: 'Propeller Push', url: 'https://propu.sh/pfe/current/tag.min.js' },
    ],
  },
  {
    id: 'cryptominers',
    name: 'Kryptokoparki',
    tests: [
      { name: 'CoinHive', url: 'https://coinhive.com/lib/coinhive.min.js' },
      { name: 'CoinHive (alt)', url: 'https://authedmine.com/lib/authedmine.min.js' },
      { name: 'JSECoin', url: 'https://load.jsecoin.com/load/0/load.js' },
      { name: 'WebMinePool', url: 'https://webminepool.com/lib/base.js' },
      { name: 'PPoi', url: 'https://ppoi.org/lib/projectpoi.min.js' },
      { name: 'NoCoin (test)', url: 'https://coin-hive.com/lib/coinhive.min.js' },
      { name: 'MineroAmino', url: 'https://minero.cc/lib/minero.min.js' },
      { name: 'DeepMiner', url: 'https://deepminer.online/miner.min.js' },
    ],
  },
  {
    id: 'malware-phishing',
    name: 'Malware, phishing i niebezpieczne domeny',
    tests: [
      { name: 'URLhaus Malware', url: 'https://urlhaus.abuse.ch/api/' },
      { name: 'Malvertising (test)', url: 'https://malware-check.disconnect.me/test' },
      { name: 'Adguard Test Malware', url: 'https://test.reliefjet.com/test.js' },
      { name: 'Fake Flash Update', url: 'https://flashupdate.info/flash.js' },
      { name: 'Suspicious TLD .tk', url: 'https://freeads.tk/ad.js' },
      { name: 'Suspicious TLD .gq', url: 'https://tracking.gq/pixel.js' },
      { name: 'Suspicious TLD .cf', url: 'https://analytics.cf/track.js' },
      { name: 'Suspicious TLD .ga', url: 'https://offers.ga/popup.js' },
      { name: 'Suspicious TLD .ml', url: 'https://downloads.ml/setup.js' },
    ],
  },
  {
    id: 'telemetry',
    name: 'Telemetria systemowa',
    tests: [
      { name: 'Microsoft Telemetry', url: 'https://vortex.data.microsoft.com/collect/v1' },
      { name: 'Microsoft Compat', url: 'https://compat.smartscreen.microsoft.com/' },
      { name: 'Windows Error Reporting', url: 'https://watson.telemetry.microsoft.com/' },
      { name: 'Apple Analytics', url: 'https://xp.apple.com/report' },
      { name: 'Samsung Analytics', url: 'https://analytics.samsungknox.com/' },
      { name: 'Huawei Analytics', url: 'https://hianalytics.huawei.com/' },
      { name: 'Xiaomi Tracking', url: 'https://tracking.miui.com/track/v4' },
      { name: 'OnePlus Analytics', url: 'https://analytics.oneplus.com/' },
      { name: 'Roku Analytics', url: 'https://logs.roku.com/' },
      { name: 'Vizio Smart TV', url: 'https://logserver.tv.vizio.com/' },
      { name: 'Amazon Fire TV', url: 'https://device-metrics-us.amazon.com/' },
      { name: 'TikTok Telemetry', url: 'https://mon.musical.ly/monitor/collect/' },
      { name: 'Yahoo ads', url: 'https://ads.yahoo.com/' },
      { name: 'Yahoo analytics', url: 'https://analytics.yahoo.com/' },
      { name: 'Yahoo udcm', url: 'https://udcm.yahoo.com/' },
      { name: 'Yahoo analytics query', url: 'https://analytics.query.yahoo.com/' },
      { name: 'Yahoo gemini', url: 'https://gemini.yahoo.com/' },
      { name: 'Yahoo adtech', url: 'https://adtech.yahooinc.com/' },
      { name: 'Yandex extmaps-api', url: 'https://extmaps-api.yandex.net/' },
      { name: 'Yandex appmetrica', url: 'https://appmetrica.yandex.ru/' },
      { name: 'Yandex adfstat', url: 'https://adfstat.yandex.ru/' },
      { name: 'Yandex metrika', url: 'https://metrika.yandex.ru/' },
      { name: 'Yandex offerwall', url: 'https://offerwall.yandex.net/' },
      { name: 'Yandex adfox', url: 'https://adfox.yandex.ru/' },
      { name: 'Unity webview', url: 'https://webview.unityads.unity3d.com/' },
    ],
  },
  {
    id: 'cookie-consent',
    name: 'Banery cookie / Consent',
    tests: [
      { name: 'CookieBot', url: 'https://consent.cookiebot.com/uc.js' },
      { name: 'OneTrust', url: 'https://cdn.cookielaw.org/scripttemplates/otSDKStub.js' },
      { name: 'Quantcast Choice', url: 'https://quantcast.mgr.consensu.org/choice/0/0/choice.js' },
      { name: 'Didomi', url: 'https://sdk.privacy-center.org/loader.js' },
      { name: 'Osano', url: 'https://cmp.osano.com/0/osano.js' },
      { name: 'Usercentrics', url: 'https://app.usercentrics.eu/browser-ui/latest/loader.js' },
      { name: 'Iubenda', url: 'https://cdn.iubenda.com/cs/iubenda_cs.js' },
    ],
  },
  {
    id: 'push-notifications',
    name: 'Powiadomienia push',
    tests: [
      { name: 'OneSignal', url: 'https://cdn.onesignal.com/sdks/OneSignalSDK.js' },
      { name: 'PushEngage', url: 'https://clientcdn.pushengage.com/sdks/pushengage-web-sdk.js' },
      { name: 'Webpushr', url: 'https://cdn.webpushr.com/sw-server.min.js' },
      { name: 'Subscribers', url: 'https://cdn.subscribers.com/assets/subscribers.js' },
      { name: 'iZooto', url: 'https://cdn.izooto.com/scripts/sdk/izooto.js' },
      { name: 'CleverPush', url: 'https://static.cleverpush.com/channel/loader/0.js' },
      { name: 'VWO Engage', url: 'https://d5phz18u4wuww.cloudfront.net/PushSDK-Latest.js' },
      { name: 'Aimtell', url: 'https://cdn.aimtell.com/trackpush/sdk.js' },
    ],
  },
  {
    id: 'video-ads',
    name: 'Reklamy wideo',
    tests: [
      { name: 'Google IMA (Video)', url: 'https://imasdk.googleapis.com/js/sdkloader/ima3.js' },
      { name: 'SpotX', url: 'https://search.spotxchange.com/js/spotx.v3.js' },
      { name: 'Connatix', url: 'https://cds.connatix.com/connatix.player.js' },
      { name: 'AdColony', url: 'https://static.adcolony.com/adc.js' },
      { name: 'Unity Ads', url: 'https://unityads.unity3d.com/show' },
      { name: 'Vungle', url: 'https://api.vungle.com/api/v5/new' },
      { name: 'FreeWheel', url: 'https://mssl.fwmrm.net/p/release/latest-JS/adm/prd/AdManager.js' },
    ],
  },
  {
    id: 'url-shorteners',
    name: 'Skracacze linków / monetizacja',
    tests: [
      { name: 'adf.ly', url: 'https://adf.ly/js/entry.js' },
      { name: 'shorte.st', url: 'https://shorte.st/js/packed.js' },
      { name: 'ouo.io', url: 'https://ouo.io/ck.php' },
      { name: 'linkvertise', url: 'https://linkvertise.com/cdn/publisher.js' },
    ],
  },
  {
    id: 'newsletters-popups',
    name: 'Newsletter popupy i marketing',
    tests: [
      { name: 'Mailchimp Popup', url: 'https://chimpstatic.com/mcjs-connected/js/users/0/0.js' },
      { name: 'OptinMonster', url: 'https://a.optinmonster.com/app/js/api.min.js' },
      { name: 'Sumo', url: 'https://load.sumo.com/' },
      { name: 'Hello Bar', url: 'https://my.hellobar.com/0.js' },
      { name: 'Privy', url: 'https://widget.privy.com/assets/widget.js' },
      { name: 'Sleeknote', url: 'https://sleeknotecustoms.sleeknote.com/0.js' },
      { name: 'ConvertFlow', url: 'https://js.convertflow.co/production/websites/0.js' },
      { name: 'Drip', url: 'https://tag.getdrip.com/0.js' },
      { name: 'Intercom', url: 'https://widget.intercom.io/widget/0' },
      { name: 'Drift', url: 'https://js.driftt.com/include/0/0.js' },
      { name: 'HubSpot Chat', url: 'https://js.hs-scripts.com/0.js' },
      { name: 'Zendesk Widget', url: 'https://static.zdassets.com/ekr/snippet.js' },
      { name: 'LiveChat', url: 'https://cdn.livechatinc.com/tracking.js' },
      { name: 'Tawk.to', url: 'https://embed.tawk.to/0/default' },
      { name: 'Freshchat', url: 'https://wchat.freshchat.com/js/widget.js' },
      { name: 'Crisp', url: 'https://client.crisp.chat/l.js' },
    ],
  },
  {
    id: 'cdn-widgets',
    name: 'Widgety CDN i skrypty 3rd party',
    tests: [
      { name: 'Gravatar', url: 'https://www.gravatar.com/avatar/00000000000000000000000000000000' },
      { name: 'WP.com Stats', url: 'https://pixel.wp.com/g.gif' },
      { name: 'Jetpack Stats', url: 'https://stats.wp.com/e-0.js' },
      { name: 'Cloudflare Insights', url: 'https://static.cloudflareinsights.com/beacon.min.js' },
      { name: 'BuySellAds', url: 'https://s3.buysellads.com/ac/bsa.js' },
      { name: 'Carbon Ads', url: 'https://cdn.carbonads.com/carbon.js' },
      { name: 'EthicalAds', url: 'https://media.ethicalads.io/media/client/ethicalads.min.js' },
      { name: 'Yandex Metrica', url: 'https://mc.yandex.ru/metrika/tag.js' },
      { name: 'Baidu Statistics', url: 'https://hm.baidu.com/hm.js' },
      { name: 'VK Pixel', url: 'https://vk.com/js/api/openapi.js' },
    ],
  },
  {
    id: 'anti-adblock',
    name: 'Skrypty anti-adblock',
    tests: [
      { name: 'BlockAdBlock', url: 'https://cdn.blockadblock.com/blockadblock.js' },
      { name: 'FuckAdBlock', url: 'https://cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js' },
      { name: 'Admiral (anti-adb)', url: 'https://v.getadmiral.com/v1/script/0.js' },
      { name: 'PageFair', url: 'https://asset.pagefair.com/measures.js' },
      { name: 'Sourcepoint', url: 'https://gdpr-tcfv2.sp-prod.net/wrapperMessagingWithoutDetection.js' },
      { name: 'Blockthrough', url: 'https://btloader.com/tag?o=0&upapi=true' },
      { name: 'Ad Recover', url: 'https://files.adrecover.com/adrcvr.js' },
      { name: 'Uponit', url: 'https://uponit.com/front.js' },
    ],
  },
  {
    id: 'native-telemetry',
    name: 'Telemetria natywna (Smart TV, IoT)',
    tests: [
      { name: 'Samsung Smart TV', url: 'https://samsungacr.com/log' },
      { name: 'Samsung Ads', url: 'https://ad.samsungadhub.com/' },
      { name: 'samsungads.com', url: 'https://samsungads.com/' },
      { name: 'smetrics.samsung.com', url: 'https://smetrics.samsung.com/' },
      { name: 'nmetrics.samsung.com', url: 'https://nmetrics.samsung.com/' },
      { name: 'samsung-com.112.2o7.net', url: 'https://samsung-com.112.2o7.net/' },
      { name: 'analytics-api.samsunghealthcn.com', url: 'https://analytics-api.samsunghealthcn.com/' },
      { name: 'Fire TV', url: 'https://device-metrics-us-2.amazon.com/' },
      { name: 'Roku Ads', url: 'https://scribe.logs.roku.com/' },
      { name: 'LG Content Store', url: 'https://ngfts.lge.com/fts/gftsDownload.lge' },
      { name: 'Vizio Inscape', url: 'https://dis.cstream.binding.samba.tv/' },
      { name: 'Sonos Tracking', url: 'https://analytics.sonos.com/' },
      { name: 'Nvidia Telemetry', url: 'https://gfe.nvidia.com/telemetry' },
      { name: 'Steam Analytics', url: 'https://steamcommunity.com/actions/LogFriendActivityUpvote' },
      { name: 'Realme iot-eu-logser', url: 'https://iot-eu-logser.realme.com/' },
      { name: 'Realme iot-logser', url: 'https://iot-logser.realme.com/' },
      { name: 'Xiaomi api.ad', url: 'https://api.ad.xiaomi.com/' },
      { name: 'Huawei metrics.data', url: 'https://metrics.data.hicloud.com/' },
      { name: 'Huawei metrics2.data', url: 'https://metrics2.data.hicloud.com/' },
      { name: 'Huawei grs', url: 'https://grs.hicloud.com/' },
      { name: 'Huawei logservice', url: 'https://logservice.hicloud.com/' },
      { name: 'Huawei logservice1', url: 'https://logservice1.hicloud.com/' },
      { name: 'OnePlus click', url: 'https://click.oneplus.cn/' },
      { name: 'OnePlus open', url: 'https://open.oneplus.net/' },
      { name: 'Apple iadsdk', url: 'https://iadsdk.apple.com/' },
      { name: 'Apple metrics.icloud', url: 'https://metrics.icloud.com/' },
      { name: 'Apple metrics.mzstatic', url: 'https://metrics.mzstatic.com/' },
      { name: 'Apple api-adservices', url: 'https://api-adservices.apple.com/' },
      { name: 'Apple books-analytics', url: 'https://books-analytics-events.apple.com/' },
      { name: 'Apple weather-analytics', url: 'https://weather-analytics-events.apple.com/' },
      { name: 'Apple notes-analytics', url: 'https://notes-analytics-events.apple.com/' },
    ],
  },
  {
    id: 'email-tracking',
    name: 'Śledzenie e-mail',
    tests: [
      { name: 'Mailchimp Tracking', url: 'https://list-manage.com/track/open.php' },
      { name: 'Mailgun Tracking', url: 'https://email.mailgun.net/o/0' },
      { name: 'HubSpot Email Tracking', url: 'https://track.hubspot.com/__ptq.gif' },
      { name: 'Constant Contact', url: 'https://r20.rs6.net/on.jsp' },
      { name: 'Campaign Monitor', url: 'https://cmail.createsend.com/t/y-o-0-0/' },
      { name: 'Return Path', url: 'https://bl.returnpath.net/' },
    ],
  },
  {
    id: 'affiliate-tracking',
    name: 'Śledzenie afiliacyjne',
    tests: [
      { name: 'Commission Junction', url: 'https://www.emjcd.com/tags/c' },
      { name: 'Impact Radius', url: 'https://d.impactradius-event.com/' },
      { name: 'ShareASale', url: 'https://www.shareasale.com/shareasale.js' },
      { name: 'ClickBank', url: 'https://www.clickbank.net/storefront/' },
      { name: 'Awin', url: 'https://www.dwin1.com/0.js' },
      { name: 'Tradedoubler', url: 'https://pi.pardot.com/pd.js' },
      { name: 'Skimlinks', url: 'https://s.skimresources.com/js/0.js' },
      { name: 'VigLink', url: 'https://cdn.viglink.com/api/vglnk.js' },
    ],
  },
  {
    id: 'retargeting',
    name: 'Retargeting i remarketing',
    tests: [
      { name: 'Google Remarketing', url: 'https://www.googleadservices.com/pagead/conversion_async.js' },
      { name: 'Facebook Custom Audience', url: 'https://www.facebook.com/tr/' },
      { name: 'AdRoll Retargeting', url: 'https://d.adroll.com/pixel/0/0' },
      { name: 'Criteo Retargeting', url: 'https://dis.criteo.com/dis/rtb/appnexus/cookieMatch.aspx' },
      { name: 'RTB House', url: 'https://creativecdn.com/tags' },
      { name: 'Perfect Audience', url: 'https://tag.perfectaudience.com/serve/0.js' },
      { name: 'Magnetic', url: 'https://ad.atdmt.com/m/a.js' },
    ],
  },
  {
    id: 'data-brokers',
    name: 'Brokerzy danych / DMP',
    tests: [
      { name: 'Oracle Data Cloud', url: 'https://tags.bluekai.com/site/0' },
      { name: 'Lotame DMP', url: 'https://tags.crwdcntrl.net/lt/c/0/sync.min.js' },
      { name: 'Salesforce DMP', url: 'https://cdn.krxd.net/controltag/0.js' },
      { name: 'Neustar', url: 'https://aa.agkn.com/adscores/g.js' },
      { name: 'Eyeota', url: 'https://ps.eyeota.net/pixel' },
      { name: 'Exelate (Nielsen)', url: 'https://loadm.exelator.com/load/' },
      { name: 'AddThis Data', url: 'https://m.addthisedge.com/live/boost/0' },
    ],
  },
]

/**
 * Get the total number of tests across all categories
 */
export function getTotalTestCount(): number {
  return TEST_CATEGORIES.reduce((sum, cat) => sum + cat.tests.length, 0)
}
