blank_issues_enabled: false
contact_links:
  - name: Kontakt
    url: https://github.com/rokartur/polish-complete-filters/discussions
    about: Jeśli potrzebujesz pomocy, masz pytania lub chcesz porozmawiać o projekcie, utwórz wątek na forum dyskusyjnym. To najlepsze miejsce, aby uzyskać wsparcie lub podzielić się swoimi pomysłami.
