import type { TestCategory } from './index'

export const adNetworks: TestCategory = {
  id: 'ad-networks',
  name: 'Sieci reklamowe',
  tests: [
    { name: 'Amazon Ads', url: 'https://z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US' },
    { name: 'Amazon Ads Tag', url: 'https://s.amazon-adsystem.com/iu3?cm3ppClass=jor498' },
    { name: 'Amazon analyticsengine', url: 'https://analyticsengine.s3.amazonaws.com/' },
    { name: 'Amazon analytics S3', url: 'https://analytics.s3.amazonaws.com/' },
    { name: 'Amazon advice-ads', url: 'https://advice-ads.s3.amazonaws.com/' },
    { name: 'Media.net', url: 'https://contextual.media.net/dmedianet.js' },
    { name: 'static.media.net', url: 'https://static.media.net/' },
    { name: 'media.net', url: 'https://media.net/' },
    { name: 'adservetx.media.net', url: 'https://adservetx.media.net/' },
    { name: 'Outbrain', url: 'https://widgets.outbrain.com/outbrain.js' },
    { name: 'Taboola', url: 'https://cdn.taboola.com/libtrc/loader.js' },
    { name: 'Criteo', url: 'https://static.criteo.net/js/ld/publishertag.prebid.js' },
    { name: 'AppNexus', url: 'https://ib.adnxs.com/ut/v3/prebid' },
    { name: 'Rubicon', url: 'https://fastlane.rubiconproject.com/a/api/fastlane.json' },
    { name: 'Index Exchange', url: 'https://htlb.casalemedia.com/headertag' },
    { name: 'ShareThrough', url: 'https://platform-api.sharethrough.com/v2.0/creative/stx-monetize' },
    { name: 'Sovrn', url: 'https://ap.lijit.com/rtb/bid' },
    { name: 'Ezoic', url: 'https://g.ezoic.net/ezoic/ezoic.js' },
    { name: 'Revcontent', url: 'https://assets.revcontent.com/master/delivery.js' },
    { name: 'MGID', url: 'https://jsc.mgid.com/site.js' },
    { name: 'PropellerAds', url: 'https://go.onclasrv.com/apu.php' },
    { name: 'PopAds', url: 'https://c1.popads.net/pop.js' },
    { name: 'Adsterra', url: 'https://www.profitabledisplaynetwork.com/b4.js' },
    { name: 'Infolinks', url: 'https://resources.infolinks.com/js/infolinks_main.js' },
    { name: 'Vibrant Media', url: 'https://ads.intellitxt.com/intellitxt/front.asp' },
    { name: 'TripleLift', url: 'https://tlx.3lift.com/header/auction' },
    { name: 'AdRoll', url: 'https://s.adroll.com/j/roundtrip.js' },
    { name: 'TradeDesk', url: 'https://js.adsrvr.org/up_loader.1.1.0.js' },
    { name: 'AdColony ads30', url: 'https://ads30.adcolony.com/' },
    { name: 'AdColony adc3-launch', url: 'https://adc3-launch.adcolony.com/' },
    { name: 'AdColony events3alt', url: 'https://events3alt.adcolony.com/' },
    { name: 'Microsoft Ads (UET)', url: 'https://bat.bing.com/bat.js' },
    { name: 'Microsoft Ads', url: 'https://ads.microsoft.com/' },
    { name: 'PubMatic', url: 'https://ads.pubmatic.com/AdServer/js/pwt/0/0/pwt.js' },
    { name: 'PubMatic (hbopenbid)', url: 'https://hbopenbid.pubmatic.com/' },
    { name: 'OpenX', url: 'https://ox-d.openx.com/w/1.0/arj' },
    { name: 'GumGum', url: 'https://g2.gumgum.com/javascripts/ggv2.js' },
    { name: '33Across', url: 'https://ssc.33across.com/api/v1/hb' },
    { name: 'Kevel (Adzerk)', url: 'https://static.adzerk.net/ados.js' },
    { name: 'Teads', url: 'https://a.teads.tv/page/0/tag' },
    { name: 'Nativo', url: 'https://s.ntv.io/serve/load.js' },
    { name: 'Spotify Ads', url: 'https://ads-fa.spotify.com/' },
    { name: 'Spotify spclient', url: 'https://spclient.wg.spotify.com/ads/' },
    { name: 'Yahoo DSP', url: 'https://s.yimg.com/wi/ytc.js' },
  ],
}
