import type { TestCategory } from './index'

export const nativeTelemetry: TestCategory = {
  id: 'native-telemetry',
  name: 'Telemetria natywna (Smart TV, IoT)',
  tests: [
    { name: 'Samsung Smart TV', url: 'https://samsungacr.com/log' },
    { name: 'Samsung Ads', url: 'https://ad.samsungadhub.com/' },
    { name: 'samsungads.com', url: 'https://samsungads.com/' },
    { name: 'smetrics.samsung.com', url: 'https://smetrics.samsung.com/' },
    { name: 'nmetrics.samsung.com', url: 'https://nmetrics.samsung.com/' },
    { name: 'samsung-com.112.2o7.net', url: 'https://samsung-com.112.2o7.net/' },
    { name: 'analytics-api.samsunghealthcn.com', url: 'https://analytics-api.samsunghealthcn.com/' },
    { name: 'Fire TV', url: 'https://device-metrics-us-2.amazon.com/' },
    { name: 'Roku Ads', url: 'https://scribe.logs.roku.com/' },
    { name: 'Vizio Inscape', url: 'https://dis.cstream.binding.samba.tv/' },
    { name: 'Sonos Tracking', url: 'https://analytics.sonos.com/' },
    { name: 'Steam Analytics', url: 'https://steamcommunity.com/actions/LogFriendActivityUpvote' },
    { name: 'Realme iot-eu-logser', url: 'https://iot-eu-logser.realme.com/' },
    { name: 'Realme iot-logser', url: 'https://iot-logser.realme.com/' },
    { name: 'Xiaomi api.ad', url: 'https://api.ad.xiaomi.com/' },
    { name: 'Huawei metrics.data', url: 'https://metrics.data.hicloud.com/' },
    { name: 'Huawei metrics2.data', url: 'https://metrics2.data.hicloud.com/' },
    { name: 'Huawei grs', url: 'https://grs.hicloud.com/' },
    { name: 'Huawei logservice', url: 'https://logservice.hicloud.com/' },
    { name: 'Huawei logservice1', url: 'https://logservice1.hicloud.com/' },
    { name: 'OnePlus click', url: 'https://click.oneplus.cn/' },
    { name: 'OnePlus open', url: 'https://open.oneplus.net/' },
    { name: 'Apple iadsdk', url: 'https://iadsdk.apple.com/' },
    { name: 'Apple metrics.icloud', url: 'https://metrics.icloud.com/' },
    { name: 'Apple metrics.mzstatic', url: 'https://metrics.mzstatic.com/' },
    { name: 'Apple api-adservices', url: 'https://api-adservices.apple.com/' },
    { name: 'Apple books-analytics', url: 'https://books-analytics-events.apple.com/' },
    { name: 'Apple weather-analytics', url: 'https://weather-analytics-events.apple.com/' },
    { name: 'Apple notes-analytics', url: 'https://notes-analytics-events.apple.com/' },
  ],
}
