import type { TestCategory } from './index'

export const polishAds: TestCategory = {
  id: 'polish-ads',
  name: 'Polskie sieci reklamowe',
  tests: [
    { name: 'WP Ads (Wirtualna Polska)', url: 'https://std.wpcdn.pl/wpjslib/wpjslib-inline.js' },
    { name: 'Allegro Analytics', url: 'https://analytics.allegro.pl/collector' },
    { name: 'adocean', url: 'https://myao.adocean.pl/files/js/ado.js' },
    { name: 'Clickonometrics', url: 'https://clickonometrics.pl/' },
    { name: 'Yieldbird', url: 'https://yieldbird.com/' },
    { name: 'Adkontekst', url: 'https://adkontekst.pl/' },
    { name: 'Onet Reklama', url: 'https://reklama.onet.pl/' },
    { name: 'WP Reklama', url: 'https://reklama.wp.pl/' },
    { name: 'Gemius', url: 'https://gapl.hit.gemius.pl/gplayer.js' },
    { name: 'Gemius (Onet)', url: 'https://onet.hit.gemius.pl/' },
    { name: 'Gemius (WP)', url: 'https://wp.hit.gemius.pl/' },
    { name: 'Gemius (TVN)', url: 'https://tvn.hit.gemius.pl/' },
    { name: 'Gemius (Interia)', url: 'https://interia.hit.gemius.pl/' },
    { name: 'SALESmanago', url: 'https://app2.salesmanago.pl/static/sm.js' },
    { name: 'edrone', url: 'https://d.edrone.me/api/init' },
    { name: 'user.com', url: 'https://widget.user.com/widget.js' },
    { name: 'SAREhub', url: 'https://data.sarehub.com/' },
    { name: 'PushPushGo', url: 'https://pushpushgo.com/' },
    { name: 'CallPage', url: 'https://callpage.io/' },
    { name: 'QuarticON (global)', url: 'https://quarticon.com/' },
    { name: 'Piwik PRO', url: 'https://piwik.pro/' },
    { name: 'GetResponse', url: 'https://cdn.getresponse.com/widget.js' },
    { name: 'Albacross', url: 'https://serve.albacross.com/track.js' },
    { name: 'Gemius (Polsat)', url: 'https://polsat.hit.gemius.pl/' },
    { name: 'Gemius (Gazeta)', url: 'https://gazeta.hit.gemius.pl/' },
    { name: 'Gemius (RMF)', url: 'https://rmf.hit.gemius.pl/' },
    { name: 'adocean (Onet)', url: 'https://onet.adocean.pl/' },
    { name: 'adocean (WP)', url: 'https://wp.adocean.pl/' },
    { name: 'adocean (Interia)', url: 'https://interia.adocean.pl/' },
  ],
}
