import type { TestCategory } from './index'

export const socialTrackers: TestCategory = {
  id: 'social-trackers',
  name: 'Trackery społecznościowe',
  tests: [
    { name: 'Facebook SDK', url: 'https://connect.facebook.net/en_US/sdk.js' },
    { name: 'Facebook Social Plugin', url: 'https://www.facebook.com/plugins/like.php' },
    { name: 'pixel.facebook.com', url: 'https://pixel.facebook.com/' },
    { name: 'Twitter Widget', url: 'https://platform.twitter.com/widgets.js' },
    { name: 'Twitter Analytics', url: 'https://static.ads-twitter.com/uwt.js' },
    { name: 'LinkedIn Insight', url: 'https://snap.licdn.com/li.lms-analytics/insight.min.js' },
    { name: 'LinkedIn Ads', url: 'https://px.ads.linkedin.com/collect' },
    { name: 'ads.linkedin.com', url: 'https://ads.linkedin.com/' },
    { name: 'analytics.pointdrive.linkedin.com', url: 'https://analytics.pointdrive.linkedin.com/' },
    { name: 'Pinterest Tag', url: 'https://s.pinimg.com/ct/core.js' },
    { name: 'ads.pinterest.com', url: 'https://ads.pinterest.com/' },
    { name: 'log.pinterest.com', url: 'https://log.pinterest.com/' },
    { name: 'TikTok Pixel', url: 'https://analytics.tiktok.com/i18n/pixel/sdk.js' },
    { name: 'ads-sg.tiktok.com', url: 'https://ads-sg.tiktok.com/' },
    { name: 'business-api.tiktok.com', url: 'https://business-api.tiktok.com/' },
    { name: 'ads.tiktok.com', url: 'https://ads.tiktok.com/' },
    { name: 'Snapchat Pixel', url: 'https://sc-static.net/scevent.min.js' },
    { name: 'Reddit Pixel', url: 'https://www.redditstatic.com/ads/pixel.js' },
    { name: 'YouTube Ads', url: 'https://ads.youtube.com/' },
    { name: 'ShareThis', url: 'https://platform-api.sharethis.com/js/sharethis.js' },
    { name: 'AddThis', url: 'https://s7.addthis.com/js/300/addthis_widget.js' },
    { name: 'Instagram Embed', url: 'https://www.instagram.com/embed.js' },
    { name: 'X (Twitter) Ads API', url: 'https://ads-api.twitter.com/' },
    { name: 'Threads Embed', url: 'https://www.threads.net/embed.js' },
    { name: 'Discord Widget', url: 'https://discord.com/api/guilds/0/widget.json' },
    { name: 'Telegram Widget', url: 'https://telegram.org/js/telegram-widget.js' },
    { name: 'WhatsApp Widget', url: 'https://web.whatsapp.com/' },
    { name: 'Quora Pixel', url: 'https://q.quora.com/_/ad/0/pixel' },
  ],
}
