import type { TestCategory } from './index'

export const trackingAnalytics: TestCategory = {
  id: 'tracking-analytics',
  name: 'Tracking i analityka',
  tests: [
    { name: 'Google Analytics', url: 'https://www.google-analytics.com/analytics.js' },
    { name: 'analytics.google.com', url: 'https://analytics.google.com/' },
    { name: 'ssl.google-analytics.com', url: 'https://ssl.google-analytics.com/' },
    { name: 'Facebook Pixel', url: 'https://connect.facebook.net/en_US/fbevents.js' },
    { name: 'Hotjar', url: 'https://static.hotjar.com/c/hotjar-0.js' },
    { name: 'Hotjar adm', url: 'https://adm.hotjar.com/' },
    { name: 'Hotjar insights', url: 'https://insights.hotjar.com/' },
    { name: 'Hotjar script', url: 'https://script.hotjar.com/' },
    { name: 'Hotjar surveys', url: 'https://surveys.hotjar.com/' },
    { name: 'Hotjar careers', url: 'https://careers.hotjar.com/' },
    { name: 'Hotjar events', url: 'https://events.hotjar.io/' },
    { name: 'Mixpanel', url: 'https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js' },
    { name: 'Heap Analytics', url: 'https://cdn.heapanalytics.com/js/heap-0.js' },
    { name: 'Amplitude', url: 'https://cdn.amplitude.com/libs/amplitude-8.21.4-min.gz.js' },
    { name: 'FullStory', url: 'https://edge.fullstory.com/s/fs.js' },
    { name: 'Lucky Orange', url: 'https://d10lpsik1i8c69.cloudfront.net/w.js' },
    { name: 'luckyorange.com', url: 'https://luckyorange.com/' },
    { name: 'api.luckyorange.com', url: 'https://api.luckyorange.com/' },
    { name: 'cdn.luckyorange.com', url: 'https://cdn.luckyorange.com/' },
    { name: 'w1.luckyorange.com', url: 'https://w1.luckyorange.com/' },
    { name: 'upload.luckyorange.net', url: 'https://upload.luckyorange.net/' },
    { name: 'cs.luckyorange.net', url: 'https://cs.luckyorange.net/' },
    { name: 'settings.luckyorange.net', url: 'https://settings.luckyorange.net/' },
    { name: 'mouseflow.com', url: 'https://mouseflow.com/' },
    { name: 'o2.mouseflow.com', url: 'https://o2.mouseflow.com/' },
    { name: 'gtm.mouseflow.com', url: 'https://gtm.mouseflow.com/' },
    { name: 'api.mouseflow.com', url: 'https://api.mouseflow.com/' },
    { name: 'tools.mouseflow.com', url: 'https://tools.mouseflow.com/' },
    { name: 'cdn-test.mouseflow.com', url: 'https://cdn-test.mouseflow.com/' },
    { name: 'Optimizely', url: 'https://cdn.optimizely.com/js/0.js' },
    { name: 'VWO', url: 'https://dev.visualwebsiteoptimizer.com/lib/0.js' },
    { name: 'Plausible', url: 'https://plausible.io/js/script.js' },
    { name: 'New Relic', url: 'https://js-agent.newrelic.com/nr-spa-1216.min.js' },
    { name: 'Sentry', url: 'https://browser.sentry-cdn.com/7.0.0/bundle.min.js' },
    { name: 'Snowplow', url: 'https://d1fc8wv8zag5ca.cloudfront.net/2.18.2/sp.js' },
    { name: 'Chartbeat', url: 'https://static.chartbeat.com/js/chartbeat.js' },
    { name: 'Comscore', url: 'https://sb.scorecardresearch.com/beacon.js' },
    { name: 'Nielsen', url: 'https://cdn-gl.imrworldwide.com/conf/0.js' },
    { name: 'Quantcast', url: 'https://secure.quantserve.com/quant.js' },
    { name: 'Keen.io', url: 'https://d26b395fwzu5fz.cloudfront.net/keen-tracking-1.4.0.min.js' },
    { name: 'Kissmetrics', url: 'https://scripts.kissmetrics.com/0.js' },
    { name: 'Parse.ly', url: 'https://cdn.parsely.com/keys/0/p.js' },
    { name: 'FreshWorks', url: 'https://freshmarketer.com/' },
    { name: 'FreshWorks claritybt', url: 'https://claritybt.freshmarketer.com/' },
    { name: 'stats.wp.com', url: 'https://stats.wp.com/' },
    { name: 'Segment', url: 'https://cdn.segment.com/analytics.js/v1/0/analytics.min.js' },
    { name: 'Segment API', url: 'https://api.segment.io/v1/t' },
    { name: 'PostHog', url: 'https://us.posthog.com/static/array.js' },
    { name: 'PostHog EU', url: 'https://eu.posthog.com/static/array.js' },
    { name: 'Pendo', url: 'https://cdn.pendo.io/agent/static/0/pendo.js' },
    { name: 'Pendo (app)', url: 'https://app.pendo.io/data/ptm.gif' },
    { name: 'mParticle', url: 'https://jssdkcdns.mparticle.com/js/v2/0/mparticle.js' },
    { name: 'RudderStack', url: 'https://cdn.rudderlabs.com/v1.1/rudder-analytics.min.js' },
    { name: 'Contentsquare', url: 'https://t.contentsquare.net/uxa/0.js' },
    { name: 'Dynatrace', url: 'https://js-cdn.dynatrace.com/jstag/0/bf.js' },
    { name: 'Datadog RUM', url: 'https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum.js' },
    { name: 'Branch.io', url: 'https://cdn.branch.io/branch-latest.min.js' },
    { name: 'AppsFlyer', url: 'https://cdn.appsflyer.com/web-sdk/v1/af.min.js' },
    { name: 'Adjust', url: 'https://cdn.adjust.com/adjust-latest.min.js' },
  ],
}
